### ISSUE TITLE
Hard code the ENPOINT and SECRET_SESSION_KEY into the app, these variables seldomly change

### ISSUE THREAD

**Issue by kn9ts** [kn9ts/project-mulla#40]
The `ENDPOINT` and `SESSION_SECRET_KEY` hardly will change.

```yaml
env_variables:
  SESSION_SECRET_KEY: '88186735405ab8d59f968ed4dab89da5515'
  ENDPOINT: 'https://safaricom.co.ke/mpesa_online/lnmo_checkout_server.php?wsdl'
```

Hardcode them into the `environment.js` file so as to reduce developer ENV config variables.
